apiVersion: apps/v1
kind: Deployment
metadata:
  name: ganache-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ganache
  template:
    metadata:
      labels:
        app: ganache
    spec:
      containers:
      - name: ganache
        image: snpsuen/ganache:v01
        ports:
        - containerPort: 8545
---
apiVersion: v1
kind: Service
metadata:
  name: ganache-service
  labels:
    app: ganache
spec:
  selector:
    app: ganache
  ports:
  - protocol: TCP
    port: 8545
    targetPort: 8545
  type: LoadBalancer
---
