apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketfront-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marketfront
  template:
    metadata:
      labels:
        app: marketfront
    spec:
      containers:
      - name: marketfront
        image: snpsuen/marketfront:v01
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: marketfront-service
  labels:
    app: marketfront
spec:
  selector:
    app: marketfront
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer
  ---
